version: "3.9"

services:
  webapp:
    build:
      context: .
    image: sandsten/vrexperiment-frontend:dev
    container_name: vrexperiment_frontend
    ports:
      - 3001:3001
    volumes:
      - ./src:/app/src # Create a bind mount to monitor changes inside /src
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
