version: "3.9"

services:
  webapp:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src # Create a bind mount to monitor changes inside /src
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
